### ISSUE TITLE
Redirect conflict with Raknetify

### ISSUE THREAD

**Issue by allinkdev** [FlorianMichael/ViaFabricPlus#11]
### Description
Neither cause the game to crash when enabled separately, so I am lead to believe that having both of these mods enabled on the same install is the cause of the crash.

### Installed Mods
- `ViaFabricPlus` 2.1.7
- `Raknetify` 0.1.0+alpha.5.61
- `Fabric API` 0.76.0+1.19.4
### Related Logs
```[03:50:44] [Render thread/INFO]: [STDOUT]: Raknetify: Using leak detector level SIMPLE
[03:50:45] [Render thread/WARN]: @Redirect conflict. Skipping viafabricplus.mixins.json:base.MixinClientConnection from mod viafabricplus->@Redirect::applyRakNetChannelFactory(Lio/netty/bootstrap/Bootstrap;Ljava/lang/Class;)Lio/netty/bootstrap/AbstractBootstrap; with priority 1000, already redirected by raknetify-fabric.mixins.json:common.MixinCCConnect from mod raknetify->@Redirect::redirectChannel(Lio/netty/bootstrap/Bootstrap;Ljava/lang/Class;Ljava/net/InetSocketAddress;Z)Lio/netty/bootstrap/AbstractBootstrap; with priority 1010
[03:50:45] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.
Time: 2023-03-18 03:50:45
Description: Initializing game
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fabric-networking-api-v1'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:468)
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'client' provided by 'fabric-networking-api-v1'
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 10 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_2535 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:68)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	... 11 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 21 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector applyRakNetChannelFactory(Lio/netty/bootstrap/Bootstrap;Ljava/lang/Class;)Lio/netty/bootstrap/AbstractBootstrap; in viafabricplus.mixins.json:base.MixinClientConnection from mod viafabricplus failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap viafabricplus-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1385)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1062)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:402)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 24 more
A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------
-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at net.minecraft.class_310.<init>(class_310.java:468)
-- Initialization --
Details:
	Modules: 
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:198)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71)
```

**Comment by FlorianMichael** [comment]
Latest Raknetify does not start for me anyway, as soon as there are stable releases I will test and see if you can make it compact, but think that it will not work with ViaFabricPlus. Does it work with ViaFabric?

**Comment by allinkdev** [comment]
> Latest Raknetify does not start for me anyway, as soon as there are stable releases I will test and see if you can make it compact, but think that it will not work with ViaFabricPlus. Does it work with ViaFabric?

Yes, ViaFabric works with the current Raknetify devbuild (which I originally ran into the issue with ViaFabricPlus on), as available on Modrinth.

**Comment by FlorianMichael** [comment]
Raknetify only doesn't work with ViaFabricPlus, because I do a lot of the same injections for the Bedrock support, because then I have to include RakNet parts, so to speak (I'm not sure if you can ever make this compact)

**Comment by FlorianMichael** [comment]
Okay, I definitely can't make Raknetify compact that easily anymore, with the new changes I just had to change too much

**Comment by FlorianMichael** [comment]
This is now fixed
