### ISSUE TITLE
The mod crashes when there's no sodium installed

### ISSUE THREAD

**Issue by Blayung** [FlorianMichael/ViaFabricPlus#56]
### General Information

- ViaFabricPlus

### Bug Description

When I launch the game with no sodium installed the game crashes on startup and throws such an error:
```
[21:59:50] [main/WARN]: Error loading class: me/jellysquid/mods/sodium/client/render/chunk/ChunkTracker (java.lang.ClassNotFoundException: me/jellysquid/mods/sodium/client/render/chunk/ChunkTracker)
[21:59:51] [main/ERROR]: Minecraft has crashed!
net.fabricmc.loader.impl.FormattedException: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/event/EventFactory
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:464) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: net/fabricmc/fabric/api/event/EventFactory
	at de.florianmichael.viafabricplus.event.PreLoadCallback.<clinit>(PreLoadCallback.java:25) ~[viafabricplus-2.5.5.jar:?]
	at de.florianmichael.viafabricplus.ViaFabricPlus.init(ViaFabricPlus.java:52) ~[viafabricplus-2.5.5.jar:?]
	at net.minecraft.client.main.Main.handler$zzd000$viafabricplus$preLoad(Main.java:532) ~[minecraft-1.19.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:152) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.fabricmc.fabric.api.event.EventFactory
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.19.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at de.florianmichael.viafabricplus.event.PreLoadCallback.<clinit>(PreLoadCallback.java:25) ~[viafabricplus-2.5.5.jar:?]
	at de.florianmichael.viafabricplus.ViaFabricPlus.init(ViaFabricPlus.java:52) ~[viafabricplus-2.5.5.jar:?]
	at net.minecraft.client.main.Main.handler$zzd000$viafabricplus$preLoad(Main.java:532) ~[minecraft-1.19.4-client.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:152) ~[minecraft-1.19.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	... 5 more
```

### Steps to Reproduce

1. Make a fresh fabric instance with no mods.
2. Install that mod.
3. Launch the game.

### Expected Behavior

The game launches and functions flawlessly.

**Comment by allinkdev** [comment]
You need to install the Fabric API.

**Comment by FlorianMichael** [comment]
You have to install the Fabric API

**Comment by Blayung** [comment]
Oh, yeah - that fixes the issue. But why does installing sodium just make the mod function normally? Is fabric api used just for the sodium rendering fix?

**Comment by FlorianMichael** [comment]
No, its for the Event System and some Fixes
