### ISSUE TITLE
Removed registry entries make client unable to join a server

### ISSUE THREAD

**Issue by fantomitechno** [FlorianMichael/ViaFabricPlus#75]
### General Information

```
Mods:
  [✔️] 3dskinlayers-fabric-1.5.3-mc1.19.4.jar
  [✔️] architectury-8.1.79-fabric.jar
  [✔️] armor-stand-editor-2.1.0+1.19.4-rc2.jar
  [✔️] BetterF3-6.0.0-Fabric-1.19.4-pre3.jar
  [✔️] bettermounthud-1.2.1.jar
  [✔️] boathud-1.1.3.jar
  [✔️] camerautils-1.19.4-1.0.4.jar
  [✔️] cem-0.7.3.jar
  [✔️] chat_heads-0.10.12-fabric-1.19.4.jar
  [✔️] CITResewn-1.1.3+1.19.4.jar
  [✔️] cloth-config-10.0.96-fabric.jar
  [✔️] continuity-3.0.0-beta.2+1.19.3.jar
  [✔️] Craftify-1.19.4-1.9.0-fabric.jar
  [✔️] DetailArmorBar-2.6.3+1.19.4-fabric.jar
  [✔️] dynamic-fps-2.2.0.jar
  [✔️] eating-animation-1.9.3.jar
  [✔️] entityculling-fabric-1.6.2-mc1.19.4.jar
  [✔️] Essential Dependencies.jar
  [✔️] Essential-fabric_1-19-4(1).jar
  [✔️] fabric-api-0.79.0+1.19.4.jar
  [✔️] fabric-carpet-1.19.4-1.4.101+v230319.jar
  [✔️] fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar
  [✔️] fallingleaves-1.15.0+1.19.4.jar
  [✔️] freecam-fabric-modrinth-1.1.9+1.19.jar
  [✔️] Gamma-Utils-1.6.14-mc1.19.4.jar
  [✔️] indium-1.0.15+mc1.19.4.jar
  [✔️] inventory-fix-0.0.3.jar
  [✔️] iris-mc1.19.4-1.6.1.jar
  [✔️] itemswapper-fabric-0.4.0-mc1.19.4.jar
  [✔️] kappa-3.0.4.jar
  [✔️] lithium-fabric-mc1.19.4-0.11.1.jar
  [✔️] malilib-fabric-1.19.4-0.15.3.jar
  [✔️] MinecraftCapes Fabric 1.19.4-12.3.0.jar
  [✔️] minihud-fabric-1.19.4-0.26.2.jar
  [✔️] modmenu-6.2.1.jar
  [✔️] NoChatReports-FABRIC-1.19.4-v2.1.1.jar
  [✔️] norecipebook-2.3+1.19.4.jar
  [✔️] notenoughanimations-fabric-1.6.3-mc1.19.4.jar
  [✔️] noxesium-0.1.8.jar
  [✔️] numeralping-1.2.0.jar
  [✔️] PetOwner-1.8.5-1.19.4+.jar
  [✔️] reeses_sodium_options-1.5.0+mc1.19.4-build.72.jar
  [✔️] replaymod-1.19.4-2.6.12.jar
  [✔️] reply-mod-1.1.0+1.19.4.jar
  [✔️] RoughlyEnoughItems-11.0.597.jar
  [✔️] RoughlyEnoughTrades-1.19.3-1.0.jar
  [✔️] showdurability-1.1.0+1.19.4.jar
  [✔️] sodium-extra-0.4.18+mc1.19.4-build.100.jar
  [✔️] sodium-fabric-mc1.19.4-0.4.10+build.24.jar
  [✔️] soundphysics-fabric-1.19.4-1.1.0.jar
  [✔️] spu-1.5.jar
  [✔️] starlight-1.1.1+fabric.ae22326(3).jar
  [✔️] status-effect-bars-1.0.2.jar
  [✔️] tia-1.19.4-1.0-fabric.jar
  [✔️] tweakeroo-fabric-1.19.4-0.16.0.jar
  [✔️] twitchchat-0.14.4b.jar
  [✔️] viafabricplus-2.6.6.jar
  [✔️] visible-barriers-2.0.1.jar
  [✔️] visuality-0.7.0.jar
  [✔️] voicechat-fabric-1.19.4-2.4.5.jar
  [✔️] waveycapes-fabric-1.3.2-mc1.19.3.jar
  [✔️] Xaeros_Minimap_23.4.0_Fabric_1.19.4.jar
  [✔️] XaerosWorldMap_1.30.0_Fabric_1.19.4.jar
```
yes too much mods I know

### Bug Description

Joining a 1.19 server in 1.19.3+ cause a problem with the latest Fabric API version (https://modrinth.com/mod/fabric-api/version/0.79.0+1.19.4)

I investigated the issue: it come from 1.19.3 removed three registry entries https://minecraft.fandom.com/wiki/Argument_types#History

And the latest Fabric API throw a big error if there is a difference in the registries.
Improve missing local registry entries error message. (FabricMC/fabric#3004)

### Steps to Reproduce

1. Join a 1.19 server in 1.19.3
2. Dont connect tadam

### Expected Behavior

Connect correctly

**Comment by allinkdev** [comment]
Please send the full stacktrace, as I am unable to reproduce this bug.

**Comment by FlorianMichael** [comment]
Please provide more details, like a kick message and log from the client and the server, if you get kicked for anything with "missing public key" or "invalid public key", uninstall NoChatReports and let me know if it works then.

**Comment by fantomitechno** [comment]
Here is the connection to the server
```
[17:03:22] [Render thread/INFO]: Connecting to mthxsurviesubs.mine.fun, 25565
[17:03:22] [Server Connector #1/WARN]: Failed to fetch the key pair
[17:03:25] [Render thread/INFO]: New minimap session initialized!
[17:03:25] [Render thread/INFO]: New world map session initialized!
[17:03:25] [Render thread/INFO]: Started 2 worker threads
[17:03:26] [Render thread/INFO]: Sending secret request to the server
[17:03:26] [Render thread/INFO]: Initializing sound physics for voice chat audio
[17:03:26] [Render thread/INFO]: Initializing Sound Physics
[17:03:26] [Render thread/INFO]: EFX Extension recognized
[17:03:26] [Render thread/INFO]: Max auxiliary sends: 2
[17:03:26] [Render thread/INFO]: Aux slot 1 created
[17:03:26] [Render thread/INFO]: Aux slot 2 created
[17:03:26] [Render thread/INFO]: Aux slot 3 created
[17:03:26] [Render thread/INFO]: Aux slot 4 created
[17:03:26] [Render thread/INFO]: EFX ready
[17:03:26] [Render thread/ERROR]: Received unknown remote registry entries from server
[17:03:26] [Render thread/ERROR]: Registry entry (minecraft:mob_effect) is missing from local registry (minecraft:command_argument_type)
[17:03:26] [Render thread/ERROR]: Registry entry (minecraft:item_enchantment) is missing from local registry (minecraft:command_argument_type)
[17:03:26] [Render thread/ERROR]: Registry entry (minecraft:entity_summon) is missing from local registry (minecraft:command_argument_type)
[17:03:26] [Render thread/ERROR]: Registry remapping failed!
net.fabricmc.fabric.impl.registry.sync.RemapException: Received 3 registry entries that are unknown to this client.
This is usually caused by a mismatched mod set between the client and server. See the client logs for more details.
The following registry entry namespaces may be related:

minecraft

	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.checkRemoteRemap(RegistrySyncManager.java:404) ~[transformed-mod-fabric-registry-sync-v0.i0:0/:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.apply(RegistrySyncManager.java:300) ~[transformed-mod-fabric-registry-sync-v0.i0:0/:?]
	at net.fabricmc.fabric.impl.registry.sync.RegistrySyncManager.lambda$receivePacket$0(RegistrySyncManager.java:134) ~[transformed-mod-fabric-registry-sync-v0.i0:0/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[transformed-mod-minecraft-v1.19.4.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[transformed-mod-minecraft-v1.19.4.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[transformed-mod-minecraft-v1.19.4.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[transformed-mod-minecraft-v1.19.4.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1174) ~[transformed-mod-minecraft-v1.19.4.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[transformed-mod-minecraft-v1.19.4.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[minecraft-1.19.4-client.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:527) ~[quilt-loader-0.18.10.jar:?]
	at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:82) ~[quilt-loader-0.18.10.jar:?]
	at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.18.10.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:234) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:269) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]
``` (yes it use Quilt here but I experienced exactly the same error on fabric, I'm just unable to find the logs)

**Comment by FlorianMichael** [comment]
"This is usually caused by a mismatched mod set between the client and server. See the client logs for more details." You can't use VFP to join modded fabric servers

**Comment by fantomitechno** [comment]
It's a vanilla server (it has some mods but only VoiceChat and some mods that create commands) and has you can see in the line following what you just quoted the namespace that cause the problem is `minecraft` not a modded one

**Comment by I-Got-You-Dead2** [comment]
Its literally modded

**Comment by I-Got-You-Dead2** [comment]
“Guys it’s a vanilla server but it has mods”

**Comment by I-Got-You-Dead2** [comment]
Some people bro

**Comment by fantomitechno** [comment]
If I remember correctly: SimpleVoiceChat, Chunky, Lithium, Starlight and then private mods I created and that had nothing to the game except some commands to go with VoiceChat and an emote system in the chat with a ressource pack

**Comment by allinkdev** [comment]
> If I remember correctly: SimpleVoiceChat, Chunky, Lithium, Starlight and then private mods I created and that had nothing to the game except some commands to go with VoiceChat and an emote system in the chat with a ressource pack

I am unable to reproduce this issue with that mod set. Please try disabling your private mods, and trying again.

**Comment by FlorianMichael** [comment]
I think the problem is simply that the versions of the mods differ, and that's why errors occur; in general, mod servers in VFP are only supported very indirectly.

**Comment by fantomitechno** [comment]
> > If I remember correctly: SimpleVoiceChat, Chunky, Lithium, Starlight and then private mods I created and that had nothing to the game except some commands to go with VoiceChat and an emote system in the chat with a ressource pack
> 
> I am unable to reproduce this issue with that mod set. Please try disabling your private mods, and trying again.

I can't disable them, I'm the developper of the mods but I'm not the owner but as they are not required on the client they won't have any problem

**Comment by fantomitechno** [comment]
> I think the problem is simply that the versions of the mods differ, and that's why errors occur; in general, mod servers in VFP are only supported very indirectly.

The only mod that require a version is Voice Chat and it's the same version on my client and the server

**Comment by FlorianMichael** [comment]
Can you remove all mods from the client and server and see if that works? I can't help you otherwise, as I said, joining different fabric servers with the same mods is generally not really supported, because mods often need the fabric API and have version-specific code.

**Comment by Felix14-v2** [comment]
> I can't disable them, I'm the developer of the mods but I'm not the owner but as they are not required on the client they won't have any problem

Then just run a local server ¯\_(ツ)_/¯

**Comment by FlorianMichael** [comment]
I'm closing it due to inactivity, you can open it again when there are updates.
